Jolly Umber Cormorant

High

# excess funds will not always be refunded to borrower when they are withdrawing

### Summary

_No response_

### Root Cause

When a borrower calls `_withdraw()` the funds sent with the call to cover any crosschain transactions is only [returned](https://github.com/sherlock-audit/2024-11-autonomint/blob/main/Blockchain/Blockchian/contracts/Core_logic/borrowing.sol#L686-L693) when there the position does not need to be protected on the downside

```solidity
File: borrowing.sol
687:         {if (result.downsideProtected > 0) {
688:             _getDownsideFromCDS(result.downsideProtected, msg.value - fee.nativeFee);
689:         } else {
690:             // Send the remaining ETH to Borrower
691:      @>     (bool sent, ) = payable(toAddress).call{value: msg.value - fee.nativeFee}("");
692:             if (!sent) revert Borrow_TransferFailed();
693:         }

```

The developer wrongly assumes that provided the `result.downsideProtected > 0` then there must be a cross chain call to request funds to cover the downside.

This is not true considering the [implementaion of the `_getDownsideFromCDS()`](https://github.com/sherlock-audit/2024-11-autonomint/blob/main/Blockchain/Blockchian/contracts/Core_logic/borrowing.sol#L725-L738) function as shown below

```solidity
File: borrowing.sol
721:     function _getDownsideFromCDS(
722:         uint128 downsideProtected,
723:         uint256 feeForOFT
724:     ) internal {
725:         if (cds.getTotalCdsDepositedAmount() < downsideProtected) {
726:             // Call the oftOrCollateralReceiveFromOtherChains function in global variables
727:             globalVariables.oftOrCollateralReceiveFromOtherChains{value: feeForOFT}(
728:                 IGlobalVariables.FunctionToDo(3),
729:                 IGlobalVariables.USDaOftTransferData(address(treasury),downsideProtected - cds.getTotalCdsDepositedAmount()),
730:                 // Since we don't need ETH, we have passed zero params
731:                 IGlobalVariables.CollateralTokenTransferData(address(0),0,0,0), 
732:                 IGlobalVariables.CallingFunction.BORROW_WITHDRAW,
733:                 msg.sender
734:             );
735:         } else {
736:             // updating downside protected from this chain in CDS
737:             cds.updateDownsideProtected(downsideProtected);
738:         }
739:         // Burn the borrow amount
740:         treasury.approveTokens(IBorrowing.AssetName.USDa, address(this), downsideProtected);
741:         bool success = usda.contractBurnFrom(address(treasury), downsideProtected);
742:         if (!success) revert Borrow_BurnFailed();
743:     }

```

Notice that the cross-chain request is invoke only when the current `TotalCdsDepositedAmount` is not enough to cover the accrued `downsideProtected`.

Hence in a situation where the funds in the current chain are enough to cover the downside, the funds sent for fees are not refunded

### Internal pre-conditions

_No response_

### External pre-conditions

_No response_

### Attack Path

_No response_

### Impact

Funds sent to cover fees are not refunded even when they are not used leadng to loss of funds and there is not way to sweep them out of the `borrowing contract.

### PoC

_No response_

### Mitigation

Consider reimplementing the logic for the fee reversal during withdrawal